[[redirects]]
  from = "https://layl.navedislam.com"
  to = "https://navedislam.com/layl"
  status = 301
  force = true

[[redirects]]
  from = "https://layl.navedislam.com/layl"
  to = "https://layl.navedislam.com"
  status = 200
  force = true